//
// CompaniesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct CompaniesResponse: Codable {

    public var success: Bool = true
    public var companies: [Company]

    public init(companies: [Company]) {
        self.companies = companies
    }
}
