//
// CompanyUsersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct CompanyUsersResponse: Codable {

    public var success: Bool = true
    public var users: [User]

    public init(users: [User]) {
        self.users = users
    }
}
