//
// InventoryResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct InventoryResponse: Codable {

    public var success: Bool = true
    public var inventory: Inventory

    public init(inventory: Inventory) {
        self.inventory = inventory
    }
}

