//
// PingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct PingResponse: Codable {

    public var success: Bool = true
    /** Contains "pong". */
    public var message: String? = "pong"
    
    public init() {}
}
