//
// PingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct PingResponse: Codable {

    /** Contains "pong". */
    public var message: String? = "pong"
}
