//
// ProductsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProductsResponse: Codable {

    public var products: [Product]

    public init(products: [Product]) {
        self.products = products
    }
}

