//
// SingleCompanyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SingleCompanyResponse: Codable {
    public var company: CompanyModel

    public init(company: CompanyModel) {
        self.company = company
    }
}
