//
// SingleCompanyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SingleCompanyResponse: Codable {
    public var success: Bool = true
    public var company: Company

    public init(company: Company) {
        self.company = company
    }
}
