//
// UserRightsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UserRightsResponse: Codable {
    public var rights: [Right]

    public init(rights: [Right]) {
        self.rights = rights
    }
}
