//
// SetRightRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SetRightRequest: Codable {

    public var companyId: Int
    public var username: String
    public var rightId: Int
    public var given: Bool
}
