//
// CompanyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Company: Codable {

    public var id: Int
    public var name: String
    public var type: CompanyType

    public init(id: Int, name: String, type: CompanyType) {
        self.id = id
        self.name = name
        self.type = type
    }
}

