//
// CompanyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CompanyModel: Codable {

    public var name: String
    public var type: CompanyType

    public init(name: String, type: CompanyType) {
        self.name = name
        self.type = type
    }
}

