//
// CompanyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CompanyType: String, Codable, CaseIterable {
    case producer = "producer"
    case merchant = "merchant"
}
