//
// InventoryItemStateType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum InventoryItemStateType: String, Codable {
    case ordered = "ordered"
    case announced = "announced"
    case checkedin = "checkedin"
    case checkedout = "checkedout"
}
