//
// InventoryModelInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Inventory: Codable {

    public var productId: Int
    public var itemsPerState: [InventoryItemStateType: [Int]]

    public init(productId: Int, itemsPerState: [InventoryItemStateType: [Int]]) {
        self.productId = productId
        self.itemsPerState = itemsPerState
    }
}
