//
// ProductModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Product: Codable {

    public var id: Int
    public var producerId: Int
    public var gtin: String?
    public var sku: String?
    public var name: String

    public init(id: Int, producerId: Int, gtin: String?, sku: String?, name: String) {
        self.id = id
        self.producerId = producerId
        self.gtin = gtin
        self.sku = sku
        self.name = name
    }
}

