//
// RightType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum RightType: String, Codable {
    case producer = "producer"
    case merchant = "merchant"
    case null = "null"
}
